//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka4KyrsKrasnov.DBword
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id_User { get; set; }
        public string Name_User { get; set; }
        public string Phone { get; set; }
        public byte[] Image { get; set; }
        public string Information_User { get; set; }
    
        public virtual Auth Auth { get; set; }
    }
}
