//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka4KyrsKrasnov.DBword
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Id_Word { get; set; }
        public string Value_Word { get; set; }
        public string Transcription_Word { get; set; }
    }
}
